server:
  port: 9091

spring:
  application:
    name: seata-server

logging:
  config: classpath:logback-spring.xml
  file:
    path: ${user.home}/logs
  extend:
    logstash-appender:
      destination: 127.0.0.1:4560
    kafka-appender:
      bootstrap-servers: 127.0.0.1:9092
      topic: logback_to_logstash

seata:
  config:
    # support: nacos 、 consul 、 apollo 、 zk  、 etcd3
    type: file
  registry:
    # support: nacos 、 eureka 、 redis 、 zk  、 consul 、 etcd3 、 sofa
    type: file
  store:
    # support: file 、 db 、 redis
    mode: raft
  server:
    raft:
      cluster: 10.57.241.59:7091,10.57.241.59:7092,10.57.241.59:7093
      snapshotInterval: 10
      applyBatch: 32
      maxAppendBufferSize: 262144
      maxReplicatorInflightMsgs: 256
      disruptorBufferSize: 16384
      electionTimeoutMs: 1000
      reporterEnabled: false
      reporterInitialDelay: 30

